name: Build docs and push to gh-pages

on:
  push:
    branches:
      - main

env:
  DOC_BRANCH: documentation

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Uses main
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Build Docs
      run: |
        npm i -g jsdoc
        jsdoc src/index.js -d .

    - name: Setup Git
      run: |
        git config --local user.name  taennan
        git config --local user.email taennan@zohomail.com

    - name: Create Branch
      run: git checkout -b ${{ env.DOC_BRANCH }}

    - name: Remove non-doc Folders
      run: rm -rf .github src package-lock.json package.json

    - name: Deploy
      run: |
        git add .
        git commit -m 'rebuilt docs'
        git push -f --set-upstream origin ${{ env.DOC_BRANCH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
